# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=500)),
                ('created_At', models.DateTimeField(verbose_name='created at')),
                ('pic_url', models.CharField(max_length=1000)),
            ],
        ),
    ]
